image: gradle:alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- deploy

build:
  stage: build
  script:
    - ./gradlew build

publish_snapshot:
  stage: deploy
  script:
  - ./gradlew clean release -x test

  environment:
    name: publish_snapshot
  when: manual
  only:
  - /release/.*$/

publish_release:
  stage: deploy
  script:
  - ./gradlew clean release -x test

  environment:
    name: publish_release
  when: manual
  only:
  - /release/.*$/
  - master
